# Generated by Django 4.2.16 on 2026-09-28 02:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField(blank=True, default='')),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('source', models.CharField(default='Hacker News', max_length=200)),
                ('author', models.CharField(blank=True, default='', max_length=200)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.CharField(default='World', max_length=100)),
                ('sentiment', models.CharField(default='Neutral', max_length=20)),
                ('sentiment_score', models.FloatField(default=0.0)),
                ('keywords', models.TextField(blank=True, default='')),
                ('popularity_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-published_at', '-popularity_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to='news.article')),
            ],
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['published_at'], name='news_articl_publish_90ca8c_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['category'], name='news_articl_categor_5c78fc_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['sentiment'], name='news_articl_sentime_27e01a_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['source'], name='news_articl_source_594688_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookmark',
            unique_together={('article',)},
        ),
    ]
